# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [1]:
import numpy as np

A = np.tile(6,(6,6))
A[1:-1,1:-1] = 0
A

array([[6, 6, 6, 6, 6, 6],
       [6, 0, 0, 0, 0, 6],
       [6, 0, 0, 0, 0, 6],
       [6, 0, 0, 0, 0, 6],
       [6, 0, 0, 0, 0, 6],
       [6, 6, 6, 6, 6, 6]])

Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [2]:
import numpy as np

A = np.tile([[3,9],[9,3]],[4,4])
A

array([[3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3]])

Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [3]:
A = np.empty([4,3])
B = np.tile(6,(3,3))
print(A)
print(B)

[[1.14796597e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 1.33511969e-306 1.51980508e-051]
 [8.61434144e-067 6.75947235e-067 2.60954906e-057]
 [1.03012321e-071 1.77267057e-051 9.59401864e-043]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [4]:
F = np.array([0,12,45.21,34,99.91])
C = (F - 32)*5/9
print('Farenheit: ',F)

print('Centigrade: ',C)

Farenheit:  [ 0.   12.   45.21 34.   99.91]
Centigrade:  [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [5]:
A = np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
print('Original: ',A,'\n---------')
print('Real: ',A.real,'   Imaginary: ',A.imag)

Original:  [1.        +0.j         0.70710678+0.70710678j] 
---------
Real:  [1.         0.70710678]    Imaginary:  [0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [6]:
A = np.array([0,10,20,40,60])
B = np.array([0,40])
print(np.in1d(A,B))

[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [7]:
A = np.array([0,10,20,40,60])
B = np.array([10,30,40])
B[np.in1d(B,A)]

array([10, 40])

Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [8]:
A = np.array([10, 10, 20, 20, 30, 30])
print('Orig array: ',A)
print(np.unique(A))
print('--------\n')

A = [[1,1],[2,3]]
print('Orig array: ',A)
print(np.unique(A))

Orig array:  [10 10 20 20 30 30]
[10 20 30]
--------

Orig array:  [[1, 1], [2, 3]]
[1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [9]:
A = np.array([0,10,20,40,60,80])
B = np.array([10,30,40,50,70])
print('Unique Values are: ', np.setxor1d(A,B))
print(np.all(A != 0))

Unique Values are:  [ 0 20 30 50 60 70 80]
False


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [10]:
A = [10,20,-10,-20]  
print(A,' --->',np.all(A),'\n')

A = [0,10,20]
print(A,' --->',np.all(A),'\n')

[10, 20, -10, -20]  ---> True 

[0, 10, 20]  ---> False 



Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [11]:
A = [10,20,-10,-20]  
print(A,' --->',np.any(A),'\n')

A = np.array([0,10,20])
print(A,' --->',np.any(A),'\n')

A = np.array([0,0])
print(A,' --->',np.any(A),'\n')

[10, 20, -10, -20]  ---> True 

[ 0 10 20]  ---> True 

[0 0]  ---> False 



Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [12]:
A = [1,2,3,4]
print('Orig Array: ',A)
print('Repeat 2 times: ',np.tile(A,2))
print('Repeat 3 times: ',np.tile(A,3))

Orig Array:  [1, 2, 3, 4]
Repeat 2 times:  [1 2 3 4 1 2 3 4]
Repeat 3 times:  [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [13]:
A = np.array([1,2,3,4,5,6])
print('Orig Array: ',A,'\n')
print('Max value index: ',np.argmax(A))
print('Min value index: ',np.argmin(A))

Orig Array:  [1 2 3 4 5 6] 

Max value index:  5
Min value index:  0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [14]:
A = np.array([1,2])
B = np.array([4,5])

print('A & B', A, '  ',B)
print('A > B', A>B)
print('A >= B', A>=B)
print('A < B',A<B)
print('A <= B', A<=B)

A & B [1 2]    [4 5]
A > B [False False]
A >= B [False False]
A < B [ True  True]
A <= B [ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [15]:
A = [[4,6],[2,1]]
print('Original:       ',A,'\n')
A = np.sort(A,axis=0)
print('Sort 1st axis:  \n',A)
print('Then Sort last axis: \n',np.sort(A,axis=1))

Original:        [[4, 6], [2, 1]] 

Sort 1st axis:  
 [[2 1]
 [4 6]]
Then Sort last axis: 
 [[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [16]:
first_names = ( 'Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery' )
last_names = ( 'Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum' )
print('Output: ',np.lexsort((first_names,last_names)))

Output:  [0 1 2 3 4]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [17]:
A = np.array([[0,10,20],[20,30,40]])
print('Original Array:\n ', A)
print('\nVal > 10 :',A[A > 10])
print('\nVal>10 - Indices :',np.nonzero(A > 10))

Original Array:
  [[ 0 10 20]
 [20 30 40]]

Val > 10 : [20 20 30 40]

Val>10 - Indices : (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [18]:
def printsize(x):
    if isinstance(x,np.ndarray):A = x
    else: A = np.array(x)
    
    print('\nArray :\n',A)
    print('Byte Size: ',A.size * A.itemsize)

printsize([5,10,3,2])

printsize(np.eye(4))


Array :
 [ 5 10  3  2]
Byte Size:  16

Array :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Byte Size:  128


## Great Job!